// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum OnlyIosEventChannelPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class OnlyIosEventChannelPigeonCodecReader: FlutterStandardReader {
}

private class OnlyIosEventChannelPigeonCodecWriter: FlutterStandardWriter {
}

private class OnlyIosEventChannelPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OnlyIosEventChannelPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OnlyIosEventChannelPigeonCodecWriter(data: data)
  }
}

class OnlyIosEventChannelPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OnlyIosEventChannelPigeonCodec(readerWriter: OnlyIosEventChannelPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IosGroupAppEventChannel {
  /// 获取ios端app groups路径
  func getAppGroupsDir() throws -> String
  /// 打开软键盘设置页面
  /// return true打开成功
  /// return false 打开失败
  func openKeyboardSettings() throws -> Bool
  /// 检查软键盘扩展是否已经启用
  /// return true已经启用
  /// return false没有启用
  func isKeyboardExtensionEnabled() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IosGroupAppEventChannelSetup {
  static var codec: FlutterStandardMessageCodec { OnlyIosEventChannelPigeonCodec.shared }
  /// Sets up an instance of `IosGroupAppEventChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IosGroupAppEventChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 获取ios端app groups路径
    let getAppGroupsDirChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ai_keyboard.IosGroupAppEventChannel.getAppGroupsDir\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppGroupsDirChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppGroupsDir()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppGroupsDirChannel.setMessageHandler(nil)
    }
    /// 打开软键盘设置页面
    /// return true打开成功
    /// return false 打开失败
    let openKeyboardSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ai_keyboard.IosGroupAppEventChannel.openKeyboardSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openKeyboardSettingsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.openKeyboardSettings()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openKeyboardSettingsChannel.setMessageHandler(nil)
    }
    /// 检查软键盘扩展是否已经启用
    /// return true已经启用
    /// return false没有启用
    let isKeyboardExtensionEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.ai_keyboard.IosGroupAppEventChannel.isKeyboardExtensionEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isKeyboardExtensionEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isKeyboardExtensionEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isKeyboardExtensionEnabledChannel.setMessageHandler(nil)
    }
  }
}
