name: Build iOS App
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Xcode project
        run: |
          cd ios
          xcodebuild clean build -project Runner.xcodeproj -scheme Runner -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: MyKeyboardApp
          path: ios/build/Release-iphoneos/
